# Generated by Django 2.2.6 on 2019-11-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_manager_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
