# Generated by Django 2.2.6 on 2019-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20191114_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_message',
            field=models.TextField(blank=True),
        ),
    ]
