# Generated by Django 2.2.6 on 2019-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='house_type',
            field=models.CharField(default='house', max_length=40),
            preserve_default=False,
        ),
    ]
