# Generated by Django 2.2.6 on 2019-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191207_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Worcester', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='Massachusetts', max_length=100),
            preserve_default=False,
        ),
    ]
