# Generated by Django 2.2.6 on 2019-12-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_current_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='energy',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.CharField(default='Well', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='hot_water',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
