# Generated by Django 2.2.6 on 2019-11-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_if_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='if_expired',
            new_name='valid',
        ),
    ]
