# Generated by Django 2.2.6 on 2019-12-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20191207_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(),
        ),
    ]
